Adapt to newest singlejar placement in bazel v0.26.0 (#55)
Build failed on `bazel` `v0.26.0` with the following error:

```
ERROR: /private/var/tmp/_bazel_enricoboccadifuoco/3aac2f4ba9b1e5eaf21b07e0e0d63f02/external/graknlabs_build_tools/bazel/BUILD:54:1: no such target '@bazel_tools//tools/jdk:singlejar/singlejar': target 'singlejar/singlejar' not declared in package 'tools/jdk' defined by /private/var/tmp/_bazel_enricoboccadifuoco/3aac2f4ba9b1e5eaf21b07e0e0d63f02/external/bazel_tools/tools/jdk/BUILD and referenced by '@graknlabs_build_tools//bazel:singlejar'
```

This pull request introduces `singlejar` definition compatible with both `v0.25.2` which is currently used by us and `v0.26.0` which is the next version.