run-bazel-rbe should account for platform it is running on (#57)
To fix #326, `//ci:run-bazel-rbe` will be utilized. However, RBE does not support building for Mac, failing with the following error:
```
ERROR: /private/var/tmp/_bazel_vmax/d2feb27241ea51489aa2f0591c0e06e6/external/bazel_toolchains/configs/ubuntu16_04_clang/9.0.0/bazel_0.25.2/cc/BUILD:45:1: in cc_toolchain_suite rule @bazel_toolchains//configs/ubuntu16_04_clang/9.0.0/bazel_0.25.2/cc:toolchain: cc_toolchain_suite '@bazel_toolchains//configs/ubuntu16_04_clang/9.0.0/bazel_0.25.2/cc:toolchain' does not contain a toolchain for cpu 'darwin'
```

Therefore, RBE builds on non-Linux systems will be ignored even if gcloud config file is present.