Implement //ci:release-validate-deps (#95)
The `//ci:release-validate-deps` can be used from the CI job to ensure that we're depending on a release instead of a snapshot dependency.

For example, if we are to release `graknlabs_grakn_core` which depends on a snapshot version of `graknlabs_common` will fail with the following error message:

```
bazel run @graknlabs_build_tools//ci:release-validate-deps graknlabs_graql graknlabs_common

RuntimeError: This commit is not releasable because there are one or more snapshot 
dependencies: ['graknlabs_common']. Check that every dependencies listed in 
dependencies/graknlabs/dependencies.bzl are all release dependencies 
(ie., depends on a tag instead of a commit).
```

If every dependency is a release dependency, it will succeed:
```
bazel run @graknlabs_build_tools//ci:release-validate-deps graknlabs_graql graknlabs_common

This repository is releasable because the dependencies
are all release dependencies: ['graknlabs_common', 'graknlabs_graql']
```