Allow release notes to contain UTF8 chars (#87)
[This run of CI](https://circleci.com/gh/graknlabs/protocol/238) failed since some PRs contained non-ASCII chars and therefore failed with the following stacktrace:
```
Traceback (most recent call last):
  File "/home/circleci/.cache/bazel/_bazel_circleci/9f69b2e90a3e4f79cd001380bef9d42c/execroot/graknlabs_protocol/bazel-out/k8-fastbuild/bin/external/graknlabs_build_tools/ci/release-notes.runfiles/graknlabs_build_tools/ci/release-notes.py", line 110, in <module>
    filepath.write(release_notes_content)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1267-1268: ordinal not in range(128)
```

This PR opens the output file with correct encoding so this error can be avoided.